# Generated by Django 5.1.1 on 2024-09-29 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_collection_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'price cant me negative'), django.core.validators.MaxValueValidator(100000, 'unusual value')]),
        ),
    ]
