# Generated by Django 5.1.1 on 2024-10-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
