# Generated by Django 5.1.1 on 2024-10-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_customer_unique_non_null_phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_non_null_phone',
        ),
    ]
