# Generated by Django 5.1.1 on 2024-10-07 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0, 'price cant me negative'), django.core.validators.MaxValueValidator(100000.0, 'unusual value')]),
        ),
    ]
