# Generated by Django 5.1.2 on 2024-10-10 08:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'price cant me negative'), django.core.validators.MaxValueValidator(Decimal('10000'), 'unusual value')]),
        ),
    ]
