# Generated by Django 5.1.2 on 2024-10-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='==', editable=False, max_length=20, null=True),
        ),
    ]
